name = "RLCraft Pengdoll"
author = "pengdoll"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feca5b6c3dcdcbe3e2b0a66f35cc5974f989c287bb01c7faf29bb051fc844c35"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
