name = "RLCraft Pengdoll"
author = "pengdoll"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fd30411ebb64d6f4abfe0f796b40399215581efcf2fec4fb033b919a4e45556"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
