name = "Pengdoll World"
author = "pengdoll"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c396149d15c7df780cf32dd5d02d22ccddbce244cadda1a8981676966d2881de"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
