name = "Pengdoll World"
author = "chanh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7d0935fc658f197e84d69c864219e09cb96e54ab7495854baa9badce5a1011e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
