name = "Pengdoll World"
author = "chanh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2b47241ddef9869f10a252e852bdf8b44d764dab25540e99faa3e0a6cd596ba"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
